name: extract-7z-action

on: push

jobs:
  file-extract:
    runs-on:	linux-latest
    steps:
      - uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ./7255-Documentation_Hub-html5_-Upload_to_GitHub.zip -d ./
